spring:
  application:
    name: backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/huaizhen
    username: root
    password:

jwt:
  secret: yourSecretKeyHere123456789892435682439065802934658
  expiration: 3600000

neo4j:
  uri: bolt://106.75.246.193:7687
  username: neo4j
  password:

llm:
  api-url: https://api.siliconflow.cn/v1/chat/completions
  api-key:
  model: Qwen/Qwen3-8B